config/routes.rb
Rails.application.routes.draw do
  resources :products_lists do
    get 'cost_calculation', on: :collection
  end
  resources :prices
  resources :products
  resources :markets

  root 'products_lists#new'
end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :prices, dependent: :destroy
  has_many :products, through: :prices
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :market
  belongs_to :product

  validates :price, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :prices, dependent: :destroy
  has_many :markets, through: :prices
  has_many :productization, dependent: :destroy
  has_many :products_list, through: :productization
  accepts_nested_attributes_for :prices, reject_if: :all_blank, allow_destroy: true
end

app/models/productization.rb
class Productization < ActiveRecord::Base
  belongs_to :product
  belongs_to :products_list
end

app/models/products_list.rb
class ProductsList < ActiveRecord::Base
  has_many :productization, dependent: :destroy
  has_many :products, through: :productization
  accepts_nested_attributes_for :productization, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  def index
    @markets = Market.all
  end

  # GET /markets/1
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  def create
    @market = Market.new(market_params)

    if @market.save
      redirect_to @market, notice: 'Market was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /markets/1
  def update
    if @market.update(market_params)
      redirect_to @market, notice: 'Market was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /markets/1
  def destroy
    @market.destroy
    redirect_to markets_url, notice: 'Market was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def market_params
      params.require(:market).permit(:name, :description, :adress)
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  def index
    @prices = Price.all
  end

  # GET /prices/1
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  def create
    @price = Price.new(price_params)

    if @price.save
      redirect_to @price, notice: 'Price was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prices/1
  def update
    if @price.update(price_params)
      redirect_to @price, notice: 'Price was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prices/1
  def destroy
    @price.destroy
    redirect_to prices_url, notice: 'Price was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def price_params
      params.require(:price).permit(:type, :market_id, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    binding.pry
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(
        :name, :description, :manufacturer, prices_attributes: [:id, :price, :market_id, :_destroy]
      )
    end
end

app/controllers/products_lists_controller.rb
class ProductsListsController < ApplicationController
  before_action :set_products_list, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @products_lists = ProductsList.all
    respond_with(@products_lists)
  end

  def show
  end

  def new
    @products_list = ProductsList.new
  end

  def edit
  end

  def create
    @products_list = ProductsList.new(products_list_params)

    if @products_list.save
      redirect_to @products_list, notice: 'Products list was successfully created.'
    else
      render :new
    end
  end

  def update
    if @products_list.update(products_list_params)
      redirect_to @products_list, notice: 'Products list was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @products_list.destroy
    redirect_to products_lists_url, notice: 'Products list was successfully destroyed.'
  end

  private

  def set_products_list
    @products_list = ProductsList.find(params[:id])
  end

  def products_list_params
    params.require(:products_list).permit(
      :name, productization_attributes: [:id, :product_id, :_destroy]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def price(product)
    prices = product.prices.map { |p| p.price }.sort
    if prices.count == 1
      prices.first.round(2)
    else
      "#{prices.first.round(2)}..#{prices.last.round(2)}"
    end
  end
end

app/helpers/products_lists_helper.rb
module ProductsListsHelper
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %a{ href: new_products_list_path }= image_tag 'logo.png', size: '50x50'

    %ul.nav.navbar-nav
      %li= link_to ProductsList.model_name.human.pluralize, products_lists_path
      %li= link_to Product.model_name.human.pluralize, products_path
      %li= link_to Market.model_name.human.pluralize, markets_path

    / TODO: before do auth

    / .pull-right
    /   %ul.nav.navbar-nav
    /     %li.dropdown
    /       %a.dropdown-toggle{'data-toggle': 'dropdown', href: '#'}
    /         = current_user.email
    /         %b.caret
    /       %ul.dropdown-menu
    /         %li= link_to(t('helpers.links.edit'), edit_polymorphic_path(current_user.profile)) if policy(current_user.profile).edit?
    /         %li= link_to t(:log_out, scope: scope), destroy_user_session_path, method: :delete
    /         - if remember_user?
    /           %li.divider
    /           %li= link_to t('profiles.back_to_previous'), previous_profiles_path, method: :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cheaper
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render 'layouts/navigation'

    .container

      - if notice
        %p.alert.alert-info= notice
      - if alert
        %p.alert.alert-warning= alert
      - if flash[:error]
        - if flash[:error].is_a?(Array)
          .alert.alert-danger
            %ul
              - flash[:error].each do |msg|
                %li= msg
        - else
          %p.alert.alert-danger= flash[:error]

      = yield

    #modal-holder= yield :modals

app/views/markets/_form.html.haml
= simple_form_for(@market) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :adress

  .form-actions
    = f.button :submit

app/views/markets/edit.html.haml
%h1 Editing market

= render 'form'

= link_to 'Show', @market
\|
= link_to 'Back', markets_path

app/views/markets/index.html.haml
%h1= Market.model_name.human.pluralize

.row
  .col-xs-offset-6.col-xs-6.form-inline.text-right.mb-10
    .form-group
      = link_to t('helpers.buttons.new'),
        new_market_path,
        class: 'btn btn-default'

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Adress
      %th.thin-column
      %th.thin-column

  %tbody
    - @markets.each do |market|
      %tr
        %td= link_to market.name, market
        %td= market.description
        %td= market.adress
        %td.text-center
          = link_to '', edit_market_path(market),
            class: 'btn btn-default glyphicon glyphicon-edit'
        %td.text-center
          = link_to '', market, method: :delete,
            class: 'btn-danger btn btn-default glyphicon glyphicon-trash'

app/views/markets/new.html.haml
%h1 New market

= render 'form'

= link_to 'Back', markets_path

app/views/markets/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @market.name
%p
  %b Description:
  = @market.description
%p
  %b Adress:
  = @market.adress

= link_to 'Edit', edit_market_path(@market)
\|
= link_to 'Back', markets_path

app/views/prices/_form.html.haml
= simple_form_for(@price) do |f|
  = f.error_notification

  .form-inputs
    = f.input :type
    = f.association :market
    = f.association :product

  .form-actions
    = f.button :submit

app/views/prices/edit.html.haml
%h1 Editing price

= render 'form'

= link_to 'Show', @price
\|
= link_to 'Back', prices_path

app/views/prices/index.html.haml
%h1 Listing prices

%table
  %thead
    %tr
      %th Type
      %th Market
      %th Product
      %th
      %th
      %th

  %tbody
    - @prices.each do |price|
      %tr
        %td= price.type
        %td= price.market
        %td= price.product
        %td= link_to 'Show', price
        %td= link_to 'Edit', edit_price_path(price)
        %td= link_to 'Destroy', price, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Price', new_price_path

app/views/prices/new.html.haml
%h1 New price

= render 'form'

= link_to 'Back', prices_path

app/views/prices/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @price.type
%p
  %b Market:
  = @price.market
%p
  %b Product:
  = @price.product

= link_to 'Edit', edit_price_path(@price)
\|
= link_to 'Back', prices_path

app/views/products/_form.html.haml
= simple_form_for(@product) do |f|
  = f.error_notification
  .row
    .col-md-6
      .form-inputs
        = f.input :name
        = f.input :description
        = f.input :manufacturer

    .col-md-6
      %h3 Prices
      #prices
        = f.simple_fields_for :prices do |price|
          = render 'price_fields', f: price
        .links
          = link_to_add_association 'add price', f, :prices

  .form-actions
    = f.button :submit

app/views/products/_price_fields.html.haml
.nested-fields
  = f.input :price
  = f.association :market
  = link_to_remove_association "remove price", f

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1= Product.model_name.human.pluralize

.row
  .col-xs-offset-6.col-xs-6.form-inline.text-right.mb-10
    .form-group
      = link_to t('helpers.buttons.new'),
        new_product_path,
        class: 'btn btn-default'

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Manufacturer
      %th Price
      %th.thin-column
      %th.thin-column

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= product.description
        %td= product.manufacturer
        %td= price(product)
        %td= link_to '', edit_product_path(product),
            class: 'btn btn-default glyphicon glyphicon-edit'
        %td= link_to '', product, method: :delete,
            class: 'btn-danger btn btn-default glyphicon glyphicon-trash'

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Manufacturer:
  = @product.manufacturer
%p
  %b Price:
  = price(@product)

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/products_lists/_form.html.haml
= simple_form_for(@products_list) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/products_lists/edit.html.haml
%h1 Editing products_list

= render 'form'

= link_to 'Show', @products_list
\|
= link_to 'Back', products_lists_path

app/views/products_lists/index.html.haml
%h1 Listing products_lists

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @products_lists.each do |products_list|
      %tr
        %td= products_list.name
        %td= link_to 'Show', products_list
        %td= link_to 'Edit', edit_products_list_path(products_list)
        %td= link_to 'Destroy', products_list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Products list', new_products_list_path

app/views/products_lists/new.html.haml
.container{ 'ng-app': 'products_lists', 'ng-controller': 'ProductsListsController as lists',
  'ng-init': 'lists.init()' }
  .col-md-6.col-md-offset-3
    %flash-message{ 'duration': '5000', 'show-close': 'true', 'on-dismiss': 'myCallback(flash);' }
      .alert.alert-success.text-center.alert-dismissible{ role: 'alert' }
        %button{ 'type': 'button', 'class': 'close', 'data-dismiss': 'alert', 'aria-label': 'Close'}
          %span{ 'aria-hidden': 'true' }
            &times;
        {{ flash.text }}
    .panel.panel-default
      .panel-heading{ 'ng-model': 'name' }
        %a{ href: '#', 'editable-text': 'products_list.name' }
          {{ products_list.name || 'Products List' }}
      .panel-body
        %form{ 'ng-submit': 'lists.add_product(product)' }
          %input.form-control.form-control-lg{ textcomplete: true,
            members: 'lists.products.items',
            'ng-model': 'product_name',
            'ng-change': 'product',
            message: 'product_name',
            type: 'text',
            'placeholder': 'Type a product name' }
      %ul.list-group{ 'ng-repeat': 'product in lists.added_products.items track by $index' }
        %li.list-group-item
          {{product.name}}
          %a.danger{ 'ng-click': 'lists.remove_product($index)' }
            %span.glyphicon.glyphicon-remove.pull-right.pt-2


    .text-center
      %button.btn.btn-primary.btn-lg{ 'ng-click': 'lists.products_lists.create()' }
        Save List
      %button.btn.btn-primary.btn-lg
        Calculate The Cost

app/views/products_lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @products_list.name

= link_to 'Edit', edit_products_list_path(@products_list)
\|
= link_to 'Back', products_lists_path